object main {
  def main(args: Array[String]): Unit = {
    val machine = new Machine()
    val environment = Map("x" -> 1, "y" -> 3)
    val expression1 = Mult(Mult(Number(3), Number(2)), Mult(Number(7), Number(6)))
    val expression2 = Mult(Number(2), Sum(Number(3), Number(6)))
    val expression3 = Sum(Mult(Var("x"), Number(3)), Var("y"))
    val expression4 = Mult(Sum(Var("z"), Number(2)), Sum(Number(4), Var("y")))
//    assert(machine.run(expression1, environment) == Number(252))
    machine.run(expression1, environment)
    println()
    machine.run(expression2, environment)
    println()
    machine.run(expression3, environment)
    println()
    machine.run(expression4, environment)
    println()
    val expression5 = <(Sum(Number(3), Number(6)), Number(5))
    val expression6 = <(Sum(Number(3), Number(6)), Sum(Mult(Var("x"), Number(3)), Var("y")))
    machine.run(expression5, environment)
    println()
    machine.run(expression6, environment)
    println()
  }
}
